name: Pipeline

on: [push, pull_request]

jobs:
  test:
    name: Testes (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Copia os ficheiros do repo
        uses: actions/checkout@v4

      - name: Instalar o Python e Poetry com cache
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Instalar dependências do projeto
        run: poetry install --no-interaction --without doc

      - name: Rodar os testes
        run: poetry run task test
